function CONFLICT_plot_correlation_between_behavioral_params(participants)
%CONFLICT_PLOT_CORRELATION_BETWEEN_BEHAVIORAL_PARAMS Summary of this function goes here
%   Detailed explanation goes here
%% Correlation between fitted parameters
behavioral_parameters = [...
    [participants.mean_risk];...
    [participants.mean_ambig_corrected];...
    [participants.mean_conflict_corrected];...
    [participants.alpha];...
    [participants.beta_conflict];...
    [participants.beta_ambig];...
    [participants.gamma];...
    ]';

% Define the names of the variables
variable_names = {'Risk', 'P(Ambig) Corrected', 'P(Conf) Corrected', 'α', 'β Conflict','β Ambig', 'Gamma'};

% Create the correlation plot with variable names
corrplot(behavioral_parameters, 'type', 'Pearson', 'VarNames', variable_names, 'TestR', 'on');


%% Ohad correlation plot
if false
    % plot([participants.mean_risk]', [participants.alpha]')
    variable_names = {'Risk', 'P(Ambig) Corrected', 'P(Conf) Corrected', 'α', 'β Conflict','β Ambig', 'Gamma'};
    behavioral_parameters = [...
        [participants.mean_risk];...
        [participants.mean_ambig_corrected];...
        [participants.mean_conflict_corrected];...
        [participants.alpha];...
        [participants.beta_conflict];...
        [participants.beta_ambig];...
        [participants.gamma];...
        ]';
    CONFLICT_correlation_matrix(behavioral_parameters, variable_names)
end
end

